knp_paginator:
  page_range: 5
  default_options:
    sort_field_name: sort           # sort field query parameter name
    sort_direction_name: direction  # sort direction query parameter name
    filter_field_name: filterField  # filter field query parameter name
    filter_value_name: filterValue  # filter value query parameter name
  template:
    pagination: 'helper/pagination.html.twig'
    sortable: 'helper/sortable.html.twig'
    filtration: '@KnpPaginator/Pagination/filtration.html.twig'  # filters template
