lexik_jwt_authentication:
    private_key_path: %kernel.root_dir%/../config/jwt/private.pem
    public_key_path:  %kernel.root_dir%/../config/jwt/public.pem
    pass_phrase:      %jwt_key_pass_phrase%
    token_ttl:        3600
